CREATE TABLE team
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(50) NOT NULL,
    logo_url            VARCHAR(255),
    creation_date       DATE NOT NULL,
    training_day        VARCHAR(10),
    training_time       VARCHAR(15),
    training_location   VARCHAR(255),
    category            VARCHAR(10) NOT NULL,
    CONSTRAINT pk_team  PRIMARY KEY (id)
);