CREATE TABLE app_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    email       VARCHAR(255) UNIQUE,
    avatar_url  VARCHAR(255),
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

ALTER TABLE team
    ADD COLUMN user_id BIGINT;

ALTER TABLE team
    ADD CONSTRAINT uc_team_user UNIQUE (user_id);

ALTER TABLE team
    ADD CONSTRAINT fk_team_on_user FOREIGN KEY (user_id) REFERENCES app_user (id);
